In [134]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.linear_model import LinearRegression,SGDRegressor
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_squared_error,mean_absolute_error,classification_report
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

In [135]:
df = pd.read_csv('dataset.csv')

In [136]:
df.head()

Meal_Id                        Name catagory  \
0  meal_id1         summer squash salad    salad   
1  meal_id2        chicken minced salad    salad   
2  meal_id3        sweet chilli almonds   chilli   
3  meal_id4             tricolour salad    salad   
4  meal_id5  gluten-free christmas cake     cake   

                                         description  Veg_Non   Nutrient  \
0  white balsamic vinegar, lemon juice, lemon rin...      veg      fiber   
1  olive oil, chicken mince, garlic (minced), oni...  non-veg      fiber   
2  almonds whole, egg white, curry leaves, salt, ...      veg  vitamin_a   
3  vinegar, honey/sugar, soy sauce, salt, garlic ...      veg      fiber   
4  christmas dry fruits (pre-soaked), orange zest...      veg  vitamin_a   

                                             Disease  \
0              obesity diabeties hypertension goitre   
1   anemia pregnancy hypertension rickets goitre ...   
2   hypertension scurvy heart_disease goitre kidn...   
3                        obesity goitre hypertension   
4                              goitre kidney_disease   

                                                Diet  Price  
0   alkaline_diet low_fat_diet ketogenic_diet low...    485  
1   low_fat_diet low_carb_diet ketogenic_diet low...    600  
2   alkaline_diet low_fat_diet paleo_diet Mediter...    255  
3   low_fat_diet ketogenic_diet low_sodium_diet h...    615  
4                                  high_protien_diet    465

In [137]:
df.drop(['Meal_Id','Name','catagory','description','Veg_Non','Nutrient','Price'],inplace=True,axis=1)

In [138]:
df.head()

Disease  \
0              obesity diabeties hypertension goitre   
1   anemia pregnancy hypertension rickets goitre ...   
2   hypertension scurvy heart_disease goitre kidn...   
3                        obesity goitre hypertension   
4                              goitre kidney_disease   

                                                Diet  
0   alkaline_diet low_fat_diet ketogenic_diet low...  
1   low_fat_diet low_carb_diet ketogenic_diet low...  
2   alkaline_diet low_fat_diet paleo_diet Mediter...  
3   low_fat_diet ketogenic_diet low_sodium_diet h...  
4                                  high_protien_diet

In [139]:
df['disease_list'] = df['Disease'].apply(lambda x : str(x).split(' '))

In [140]:
df['diet_list'] = df['Diet'].apply(lambda x : str(x).split(' '))

In [141]:
df.head()

Disease  \
0              obesity diabeties hypertension goitre   
1   anemia pregnancy hypertension rickets goitre ...   
2   hypertension scurvy heart_disease goitre kidn...   
3                        obesity goitre hypertension   
4                              goitre kidney_disease   

                                                Diet  \
0   alkaline_diet low_fat_diet ketogenic_diet low...   
1   low_fat_diet low_carb_diet ketogenic_diet low...   
2   alkaline_diet low_fat_diet paleo_diet Mediter...   
3   low_fat_diet ketogenic_diet low_sodium_diet h...   
4                                  high_protien_diet   

                                        disease_list  \
0       [, obesity, diabeties, hypertension, goitre]   
1  [, anemia, pregnancy, hypertension, rickets, g...   
2  [, hypertension, scurvy, heart_disease, goitre...   
3                  [, obesity, goitre, hypertension]   
4                         [, goitre, kidney_disease]   

                                           diet_list  
0  [, alkaline_diet, low_fat_diet, ketogenic_diet...  
1  [, low_fat_diet, low_carb_diet, ketogenic_diet...  
2  [, alkaline_diet, low_fat_diet, paleo_diet, Me...  
3  [, low_fat_diet, ketogenic_diet, low_sodium_di...  
4                              [, high_protien_diet]

In [142]:
df = df.explode('disease_list')

In [143]:
df.head()

Disease  \
0   obesity diabeties hypertension goitre   
0   obesity diabeties hypertension goitre   
0   obesity diabeties hypertension goitre   
0   obesity diabeties hypertension goitre   
0   obesity diabeties hypertension goitre   

                                                Diet  disease_list  \
0   alkaline_diet low_fat_diet ketogenic_diet low...                 
0   alkaline_diet low_fat_diet ketogenic_diet low...       obesity   
0   alkaline_diet low_fat_diet ketogenic_diet low...     diabeties   
0   alkaline_diet low_fat_diet ketogenic_diet low...  hypertension   
0   alkaline_diet low_fat_diet ketogenic_diet low...        goitre   

                                           diet_list  
0  [, alkaline_diet, low_fat_diet, ketogenic_diet...  
0  [, alkaline_diet, low_fat_diet, ketogenic_diet...  
0  [, alkaline_diet, low_fat_diet, ketogenic_diet...  
0  [, alkaline_diet, low_fat_diet, ketogenic_diet...  
0  [, alkaline_diet, low_fat_diet, ketogenic_diet...

In [144]:
df = df.explode('diet_list')

In [145]:
df.tail()

Disease  \
511   obesity diabeties anemia   
511   obesity diabeties anemia   
511   obesity diabeties anemia   
511   obesity diabeties anemia   
511   obesity diabeties anemia   

                                                  Diet disease_list  \
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   

             diet_list  
511                     
511  high_protien_diet  
511         vegan_diet  
511          dash_diet  
511     ketogenic_diet

In [146]:
len(df)

18615

In [147]:
df.tail()

Disease  \
511   obesity diabeties anemia   
511   obesity diabeties anemia   
511   obesity diabeties anemia   
511   obesity diabeties anemia   
511   obesity diabeties anemia   

                                                  Diet disease_list  \
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   

             diet_list  
511                     
511  high_protien_diet  
511         vegan_diet  
511          dash_diet  
511     ketogenic_diet

In [148]:
df.iloc[511,3]

''

In [149]:
condtion = df['diet_list'] == ''
condtion

0       True
0      False
0      False
0      False
0      False
       ...  
511     True
511    False
511    False
511    False
511    False
Name: diet_list, Length: 18615, dtype: bool

In [150]:
df_new = df[~condtion]

In [151]:
df_new.head()

Disease  \
0   obesity diabeties hypertension goitre   
0   obesity diabeties hypertension goitre   
0   obesity diabeties hypertension goitre   
0   obesity diabeties hypertension goitre   
0   obesity diabeties hypertension goitre   

                                                Diet disease_list  \
0   alkaline_diet low_fat_diet ketogenic_diet low...                
0   alkaline_diet low_fat_diet ketogenic_diet low...                
0   alkaline_diet low_fat_diet ketogenic_diet low...                
0   alkaline_diet low_fat_diet ketogenic_diet low...                
0   alkaline_diet low_fat_diet ketogenic_diet low...                

         diet_list  
0    alkaline_diet  
0     low_fat_diet  
0   ketogenic_diet  
0  low_sodium_diet  
0  high_fiber_diet

In [152]:
len(df_new)

15976

In [153]:
condtions = df_new['disease_list'] == ''
condtions

0       True
0       True
0       True
0       True
0       True
       ...  
511    False
511    False
511    False
511    False
511    False
Name: disease_list, Length: 15976, dtype: bool

In [154]:
df_org = df_new[~condtions]

In [155]:
df_org

Disease  \
0     obesity diabeties hypertension goitre   
0     obesity diabeties hypertension goitre   
0     obesity diabeties hypertension goitre   
0     obesity diabeties hypertension goitre   
0     obesity diabeties hypertension goitre   
..                                      ...   
511                obesity diabeties anemia   
511                obesity diabeties anemia   
511                obesity diabeties anemia   
511                obesity diabeties anemia   
511                obesity diabeties anemia   

                                                  Diet disease_list  \
0     alkaline_diet low_fat_diet ketogenic_diet low...      obesity   
0     alkaline_diet low_fat_diet ketogenic_diet low...      obesity   
0     alkaline_diet low_fat_diet ketogenic_diet low...      obesity   
0     alkaline_diet low_fat_diet ketogenic_diet low...      obesity   
0     alkaline_diet low_fat_diet ketogenic_diet low...      obesity   
..                                                 ...          ...   
511   high_protien_diet vegan_diet dash_diet ketoge...    diabeties   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   

             diet_list  
0        alkaline_diet  
0         low_fat_diet  
0       ketogenic_diet  
0      low_sodium_diet  
0      high_fiber_diet  
..                 ...  
511     ketogenic_diet  
511  high_protien_diet  
511         vegan_diet  
511          dash_diet  
511     ketogenic_diet  

[13255 rows x 4 columns]

In [156]:
df = df_org.copy()

In [157]:
df

Disease  \
0     obesity diabeties hypertension goitre   
0     obesity diabeties hypertension goitre   
0     obesity diabeties hypertension goitre   
0     obesity diabeties hypertension goitre   
0     obesity diabeties hypertension goitre   
..                                      ...   
511                obesity diabeties anemia   
511                obesity diabeties anemia   
511                obesity diabeties anemia   
511                obesity diabeties anemia   
511                obesity diabeties anemia   

                                                  Diet disease_list  \
0     alkaline_diet low_fat_diet ketogenic_diet low...      obesity   
0     alkaline_diet low_fat_diet ketogenic_diet low...      obesity   
0     alkaline_diet low_fat_diet ketogenic_diet low...      obesity   
0     alkaline_diet low_fat_diet ketogenic_diet low...      obesity   
0     alkaline_diet low_fat_diet ketogenic_diet low...      obesity   
..                                                 ...          ...   
511   high_protien_diet vegan_diet dash_diet ketoge...    diabeties   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   
511   high_protien_diet vegan_diet dash_diet ketoge...       anemia   

             diet_list  
0        alkaline_diet  
0         low_fat_diet  
0       ketogenic_diet  
0      low_sodium_diet  
0      high_fiber_diet  
..                 ...  
511     ketogenic_diet  
511  high_protien_diet  
511         vegan_diet  
511          dash_diet  
511     ketogenic_diet  

[13255 rows x 4 columns]

In [158]:
df.drop(['Disease','Diet'],inplace=True,axis=1)

In [159]:
df

disease_list          diet_list
0        obesity      alkaline_diet
0        obesity       low_fat_diet
0        obesity     ketogenic_diet
0        obesity    low_sodium_diet
0        obesity    high_fiber_diet
..           ...                ...
511    diabeties     ketogenic_diet
511       anemia  high_protien_diet
511       anemia         vegan_diet
511       anemia          dash_diet
511       anemia     ketogenic_diet

[13255 rows x 2 columns]

In [160]:
df = df.drop_duplicates(subset=['disease_list','diet_list'])

In [161]:
len(df)

185

In [162]:
df.diet_list.unique()

array(['alkaline_diet', 'low_fat_diet', 'ketogenic_diet',
       'low_sodium_diet', 'high_fiber_diet', 'high_protien_diet',
       'dash_diet', 'low_carb_diet', 'vegan_diet', 'hormone_diet',
       'type_a_diet', 'paleo_diet', 'Mediterranean_diet',
       'gluten_free_diet', 'omni_diet', 'type_o_diet'], dtype=object)

In [163]:
encoder = LabelEncoder()
scaler = MinMaxScaler()

In [164]:
encoder.fit(df['disease_list'])

LabelEncoder()

In [165]:
X_value = encoder.transform(df['disease_list'])

In [166]:
len(X_value)
X_value = X_value.reshape(185,1)

In [167]:
X = scaler.fit_transform(X_value)

In [168]:
encoder2 = LabelEncoder()

In [169]:
encoder2.fit(df['diet_list'])

LabelEncoder()

In [170]:
y_value = encoder2.transform(df['diet_list'])

In [171]:
y = y_value.reshape(185,1)

In [172]:
X,y

(array([[0.72727273],
        [0.72727273],
        [0.72727273],
        [0.72727273],
        [0.72727273],
        [0.72727273],
        [0.72727273],
        [0.18181818],
        [0.18181818],
        [0.18181818],
        [0.18181818],
        [0.18181818],
        [0.18181818],
        [0.18181818],
        [0.54545455],
        [0.54545455],
        [0.54545455],
        [0.54545455],
        [0.54545455],
        [0.54545455],
        [0.54545455],
        [0.36363636],
        [0.36363636],
        [0.36363636],
        [0.36363636],
        [0.36363636],
        [0.36363636],
        [0.36363636],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.81818182],
        [0.81818182],
        [0.81818182],
        [0.81818182],
        [0.81818182],
        [0.81818182],
        [0.81818182],
        [0.81818182],
        [0

In [173]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size=0.3)

In [174]:
model = KNeighborsClassifier(n_neighbors=5)

In [175]:
model.fit(xtrain,ytrain)

C:\Users\amith\Envs\workshop\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [176]:
ypred = model.predict(xtest)

In [177]:
ypred[5:10]

array([2, 4, 0, 0, 3])

In [178]:
ytest[5:10]

array([[10],
       [ 6],
       [15],
       [ 6],
       [ 0]])

In [179]:
y[:10]

array([[ 1],
       [ 9],
       [ 7],
       [10],
       [ 4],
       [ 5],
       [ 2],
       [ 1],
       [ 9],
       [ 7]])

In [180]:
y_predict = model.predict(X)

In [181]:
y_predict

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 0,
       0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4,
       4, 4, 4, 4, 4, 4, 0, 0, 3, 3, 3, 3, 4, 4, 4, 4, 4, 2, 0, 0, 0, 0,
       0, 0, 4, 4, 2, 2, 2, 2, 2, 0, 2, 4, 4, 4, 0, 0, 0, 4, 4, 4, 3, 3,
       2, 2, 4, 0, 2, 4, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 4, 4, 4,
       0, 0, 0, 3, 2, 0, 0, 4, 2, 4, 2, 0, 0, 4, 2, 2, 4, 4, 0, 0, 2, 2,
       0, 2, 2, 2, 2, 0, 0, 2, 2])

In [182]:
mse = mean_squared_error(y,y_predict)

In [183]:
mae = mean_absolute_error(y,y_predict)
mae

5.718918918918919

In [184]:
y_value[:1]

array([1])

In [185]:
y[:1]

array([[1]])

In [186]:
y_predict[:1]

array([2])

In [187]:
count = 0
for i in range(len(y_predict)):
    if i % 1 == 0:
        if 0 < np.abs(y[i]-y_predict[i]) < 3:
            print(f"i: {i} <-> true value: {y[i]} <-> predicted value :{y_predict[i]}")
            count += 1
print(f"count: {count}")

i: 0 <-> true value: [1] <-> predicted value :2
i: 4 <-> true value: [4] <-> predicted value :2
i: 7 <-> true value: [1] <-> predicted value :2
i: 11 <-> true value: [4] <-> predicted value :2
i: 19 <-> true value: [5] <-> predicted value :4
i: 20 <-> true value: [2] <-> predicted value :4
i: 21 <-> true value: [1] <-> predicted value :0
i: 27 <-> true value: [2] <-> predicted value :0
i: 34 <-> true value: [6] <-> predicted value :4
i: 35 <-> true value: [5] <-> predicted value :4
i: 43 <-> true value: [6] <-> predicted value :4
i: 44 <-> true value: [5] <-> predicted value :4
i: 48 <-> true value: [6] <-> predicted value :4
i: 68 <-> true value: [4] <-> predicted value :3
i: 70 <-> true value: [5] <-> predicted value :3
i: 78 <-> true value: [1] <-> predicted value :2
i: 81 <-> true value: [0] <-> predicted value :2
i: 83 <-> true value: [4] <-> predicted value :2
i: 92 <-> true value: [5] <-> predicted value :4
i: 93 <-> true value: [2] <-> predicted value :4
i: 96 <-> true value: [

In [188]:
print(classification_report(y,y_predict))

              precision    recall  f1-score   support

           0       0.06      0.25      0.10        12
           1       0.00      0.00      0.00        12
           2       0.07      0.33      0.11        12
           3       0.06      0.09      0.07        11
           4       0.06      0.33      0.11        12
           5       0.00      0.00      0.00        12
           6       0.00      0.00      0.00        12
           7       0.00      0.00      0.00        12
           8       0.00      0.00      0.00        12
           9       0.00      0.00      0.00        12
          10       0.00      0.00      0.00        12
          11       0.00      0.00      0.00        11
          12       0.00      0.00      0.00        12
          13       0.00      0.00      0.00        12
          14       0.00      0.00      0.00         7
          15       0.00      0.00      0.00        12

    accuracy                           0.06       185
   macro avg       0.02   

C:\Users\amith\Envs\workshop\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\amith\Envs\workshop\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\amith\Envs\workshop\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
