In [1]:
import spacy
import numpy as np
import pandas as pd

CREATE VOCABULARY FIRST

In [2]:
df = pd.read_csv('spam.csv')

In [3]:
df.head()

title  \
0                          ?? the secrets to SUCCESS   
1                    ?? You Earned 500 GCLoot Points   
2                         ?? Your GitHub launch code   
3  [The Virtual Reward Center] Re: ** Clarifications   
4  10-1 MLB Expert Inside, Plus Everything You Ne...   

                                                text      type  
0  Hi James,\n\nHave you claim your complimentary...      spam  
1  \nalt_text\nCongratulations, you just earned\n...  not spam  
2  Here's your GitHub launch code, @Mortyj420!\n ...  not spam  
3  Hello,\n \nThank you for contacting the Virtua...  not spam  
4  Hey Prachanda Rawal,\n\nToday's newsletter is ...      spam

In [4]:
df['type'].value_counts()

type
not spam    58
spam        26
Name: count, dtype: int64

In [5]:
df.drop(['title'],inplace=True,axis=1)

In [6]:
df.head()

text      type
0  Hi James,\n\nHave you claim your complimentary...      spam
1  \nalt_text\nCongratulations, you just earned\n...  not spam
2  Here's your GitHub launch code, @Mortyj420!\n ...  not spam
3  Hello,\n \nThank you for contacting the Virtua...  not spam
4  Hey Prachanda Rawal,\n\nToday's newsletter is ...      spam

In [7]:
df['spam or not'] = df['type'].apply(lambda x:1 if x=='spam' else 0)

In [8]:
df.head()

text      type  spam or not
0  Hi James,\n\nHave you claim your complimentary...      spam            1
1  \nalt_text\nCongratulations, you just earned\n...  not spam            0
2  Here's your GitHub launch code, @Mortyj420!\n ...  not spam            0
3  Hello,\n \nThank you for contacting the Virtua...  not spam            0
4  Hey Prachanda Rawal,\n\nToday's newsletter is ...      spam            1

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
xtrain,xtest,ytrain,ytest = train_test_split(df['text'],df['spam or not'],test_size=0.2)

In [11]:
xtrain.shape,xtest.shape,ytrain.shape,ytest.shape

((67,), (17,), (67,), (17,))

In [12]:
from sklearn.feature_extraction.text import CountVectorizer


In [13]:
v = CountVectorizer()

In [14]:
x_train_cv = v.fit_transform(xtrain.values)

In [15]:
x_train_cv.toarray()[:1].shape

(1, 2565)

In [16]:
v.get_feature_names_out()[200:250]

array(['again', 'against', 'age', 'agency', 'agent', 'agree', 'ai', 'aim',
       'airline', 'airport', 'alain', 'alcohol', 'alcoholic', 'alert',
       'alex', 'alexxuzy', 'algebra', 'algorithms', 'align', 'aliwal',
       'alkaline', 'all', 'allow', 'allowance', 'allowed', 'allowing',
       'allows', 'almost', 'alon', 'alone', 'along', 'alpha', 'already',
       'also', 'alt_text', 'aluminium', 'always', 'am', 'amazing',
       'amazon', 'amended', 'american', 'amit', 'among', 'amphitheatre',
       'an', 'analysis', 'analyst', 'anambra', 'anambrafashion'],
      dtype=object)

In [17]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',

In [18]:
v.vocabulary_

{'this': 2303,
 'is': 1234,
 'an': 245,
 'email': 816,
 'message': 1482,
 'sent': 2041,
 'automatically': 341,
 'by': 448,
 'microsoft': 1486,
 'outlook': 1641,
 'while': 2510,
 'testing': 2283,
 'the': 2290,
 'settings': 2051,
 'for': 960,
 'your': 2553,
 'account': 160,
 'hello': 1087,
 'walid': 2475,
 'our': 1636,
 'zoom': 2564,
 'call': 458,
 'meeting': 1475,
 'tomorrow': 2332,
 'thursday': 2316,
 'july': 1276,
 '20th': 56,
 'at': 323,
 '3pm': 86,
 'est': 855,
 'new': 1550,
 'york': 2550,
 'time': 2320,
 'register': 1909,
 'free': 974,
 'space': 2139,
 'here': 1093,
 'it': 1242,
 'called': 460,
 'money': 1507,
 'you': 2551,
 'sleep': 2109,
 'll': 1373,
 'learn': 1332,
 'how': 1127,
 'possible': 1754,
 'to': 2325,
 'earn': 789,
 'income': 1169,
 '24': 65,
 'hours': 1124,
 'day': 686,
 'yes': 2546,
 'even': 863,
 'host': 1120,
 'will': 2517,
 'reveal': 1964,
 'little': 1370,
 'known': 1298,
 'almost': 227,
 'secret': 2020,
 'side': 2082,
 'hustle': 1132,
 'which': 2509,
 'enabling': 

In [19]:
x_train_np = x_train_cv.toarray()

In [20]:
x_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 2],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
indices = np.where(x_train_np[0]!=0)

In [22]:
for i in indices:
    print(x_train_np[0,i])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [23]:
from sklearn.naive_bayes import MultinomialNB

In [24]:
model = MultinomialNB()

In [25]:
model.fit(x_train_cv,ytrain)

MultinomialNB()

In [26]:
xtest_cv = v.transform(xtest)

In [27]:
from sklearn.metrics import classification_report

In [28]:
y_pred = model.predict(xtest_cv)

In [29]:
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.92      0.88        12
           1       0.75      0.60      0.67         5

    accuracy                           0.82        17
   macro avg       0.80      0.76      0.77        17
weighted avg       0.82      0.82      0.82        17



In [30]:
text = xtest[:1]
text

55    Greetings from SFI...let's keep building somet...
Name: text, dtype: object

In [31]:
prediction = model.predict(v.transform(text))

In [32]:
prediction

array([0], dtype=int64)

In [33]:
from sklearn.pipeline import Pipeline

In [34]:
clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [35]:
clf.fit(xtrain,ytrain)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [36]:
pred = clf.predict(xtest)

In [37]:
pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int64)