In [1]:
import gensim.downloader as api
wc = api.load('word2vec-google-news-300')

In [20]:
import pandas as pd
import numpy as np

In [17]:
import spacy
nlp = spacy.load('en_core_web_lg')

In [2]:
print(api.info())

{'corpora': {'semeval-2016-2017-task3-subtaskBC': {'num_records': -1, 'record_format': 'dict', 'file_size': 6344358, 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/semeval-2016-2017-task3-subtaskB-eng/__init__.py', 'license': 'All files released for the task are free for general research use', 'fields': {'2016-train': ['...'], '2016-dev': ['...'], '2017-test': ['...'], '2016-test': ['...']}, 'description': 'SemEval 2016 / 2017 Task 3 Subtask B and C datasets contain train+development (317 original questions, 3,169 related questions, and 31,690 comments), and test datasets in English. The description of the tasks and the collected data is given in sections 3 and 4.1 of the task paper http://alt.qcri.org/semeval2016/task3/data/uploads/semeval2016-task3-report.pdf linked in section “Papers” of https://github.com/RaRe-Technologies/gensim-data/issues/18.', 'checksum': '701ea67acd82e75f95e1d8e62fb0ad29', 'file_name': 'semeval-2016-2017-task3-subtaskBC.gz',

In [4]:
wc.similarity(w1='good',w2='great')

0.729151

In [8]:
wc_great = wc['great']
wc_good = wc['good']
wc_great,wc_great.shape

(array([ 7.17773438e-02,  2.08007812e-01, -2.84423828e-02,  1.78710938e-01,
         1.32812500e-01, -9.96093750e-02,  9.61914062e-02, -1.16699219e-01,
        -8.54492188e-03,  1.48437500e-01, -3.34472656e-02, -1.85546875e-01,
         4.10156250e-02, -8.98437500e-02,  2.17285156e-02,  6.93359375e-02,
         1.80664062e-01,  2.22656250e-01, -1.00585938e-01, -6.93359375e-02,
         1.04427338e-04,  1.60156250e-01,  4.07714844e-02,  7.37304688e-02,
         1.53320312e-01,  6.78710938e-02, -1.03027344e-01,  4.17480469e-02,
         4.27246094e-02, -1.10351562e-01, -6.68945312e-02,  4.19921875e-02,
         2.50000000e-01,  2.12890625e-01,  1.59179688e-01,  1.44653320e-02,
        -4.88281250e-02,  1.39770508e-02,  3.55529785e-03,  2.09960938e-01,
         1.52343750e-01, -7.32421875e-02,  2.16796875e-01, -5.76171875e-02,
        -2.84423828e-02, -3.60107422e-03,  1.52343750e-01, -2.63671875e-02,
         2.13623047e-02, -1.51367188e-01,  1.04003906e-01,  3.18359375e-01,
        -1.8

In [11]:
df = pd.read_csv('spam.csv')
df.head()

title  \
0                          ?? the secrets to SUCCESS   
1                    ?? You Earned 500 GCLoot Points   
2                         ?? Your GitHub launch code   
3  [The Virtual Reward Center] Re: ** Clarifications   
4  10-1 MLB Expert Inside, Plus Everything You Ne...   

                                                text      type  
0  Hi James,\n\nHave you claim your complimentary...      spam  
1  \nalt_text\nCongratulations, you just earned\n...  not spam  
2  Here's your GitHub launch code, @Mortyj420!\n ...  not spam  
3  Hello,\n \nThank you for contacting the Virtua...  not spam  
4  Hey Prachanda Rawal,\n\nToday's newsletter is ...      spam

In [12]:
df.type.value_counts()

type
not spam    58
spam        26
Name: count, dtype: int64

In [14]:
df['y'] = df['type'].apply(lambda x: 1 if x == 'spam' else 0)

In [24]:
def preprocessing_and_vectorizing(text):
    L = []
    doc = nlp(text)
    for token in doc:
        if token.is_punct or token.is_stop:
            continue
        else:
            L.append(token.lemma_)
    return wc.get_mean_vector(L)

In [19]:
wc.get_mean_vector(['worry','understand'])

array([ 0.00235079, -0.00284596, -0.03638233,  0.00413919, -0.10635224,
        0.05758579,  0.13348952, -0.00689176,  0.05995331, -0.02875906,
       -0.02279907, -0.06939262, -0.01549996,  0.03538099, -0.0873947 ,
        0.10044542,  0.02490648,  0.11501945,  0.00442711, -0.07228819,
       -0.04447255,  0.02785169,  0.03338735,  0.02222995,  0.07053161,
        0.06723307,  0.03483712, -0.0873695 ,  0.04152397, -0.0969665 ,
       -0.00914938,  0.00555944, -0.0277799 , -0.00701522,  0.05281431,
       -0.01066206,  0.02466576,  0.02378148,  0.0279402 ,  0.05527755,
        0.01359304, -0.01062085,  0.06734448, -0.03492254, -0.08421434,
       -0.04324378, -0.03578918, -0.00817786, -0.02093195,  0.01856531,
       -0.07064191,  0.05023994, -0.03036207, -0.0412168 , -0.00684169,
        0.05189689, -0.04097777, -0.05789134,  0.044417  , -0.0470418 ,
       -0.01475445,  0.01373999, -0.00459672,  0.00419459,  0.04307397,
       -0.01500929, -0.08037488,  0.05358911, -0.0211829 , -0.00

In [23]:
np.mean([wc_good,wc_great],axis=0)

array([ 5.61523438e-02,  1.35253906e-01, -2.29492188e-02,  1.28662109e-01,
        8.27636719e-02, -5.61218262e-02,  5.29174805e-02,  3.41796875e-03,
       -1.50146484e-02,  1.50390625e-01, -4.58984375e-02, -1.45996094e-01,
        3.11279297e-02,  2.29492188e-02, -5.50537109e-02,  1.23046875e-01,
        2.26074219e-01,  1.80175781e-01, -1.37207031e-01, -1.05468750e-01,
       -1.53286457e-02,  1.78222656e-01,  3.90625000e-03,  9.93652344e-02,
        2.03613281e-01,  9.74121094e-02, -1.27685547e-01,  3.68652344e-02,
        2.70385742e-02, -6.19812012e-02, -9.79003906e-02,  2.60925293e-02,
        2.44628906e-01,  6.42089844e-02,  1.49902344e-01,  7.26623535e-02,
       -4.69970703e-02,  3.94592285e-02,  1.44729614e-02,  1.33056641e-01,
        1.99218750e-01, -1.39160156e-01,  2.26562500e-01, -3.31115723e-02,
       -2.56958008e-02,  2.35900879e-02,  1.29394531e-01, -3.10058594e-02,
        5.43823242e-02, -1.04248047e-01,  9.44824219e-02,  2.76855469e-01,
       -1.43310547e-01,  

In [25]:
df['X'] = df['title'].apply(lambda x:preprocessing_and_vectorizing(x))

ValueError: cannot compute mean with no input